#!/bin/bash
#
# Links all executable scripts into the users local bin directory
# This will enusre there are no duplicate script file names before linking

cd "$(dirname "${BASH_SOURCE[0]}")"

# Get all executable scripts in the scripts repository
scripts="$(find "$(pwd)" \
	-name .git -prune -o \
	-name "$(basename ${BASH_SOURCE[0]})" -prune -o \
	-type f -executable -print)"

# Ensure no duplicate script names
if [[ "$(echo "$scripts" | xargs -I% basename % | uniq -d)" ]]
then
	echo "Duplicate script names exist! Aborting symbolic linking."
	exit 1
fi

# Link all executable scripts into the bin directory
echo "$scripts" | xargs -I% ln -fs % "$HOME/.local/bin/"
