#!/bin/bash

export MPD_HOST=htpc

TITLE=$(mpc playlist | sed -E 's/([^\-]+)-.*/\1/g' | dmenu -i -b -p "Digitally Imported");
[ "$TITLE" = "" ] && exit
mpc play $(mpc playlist | grep -n "^$TITLE" | awk -F: '{print $1}')
