#!/usr/bin/env ruby

require 'json'
require 'net/http'

def seconds_to_time(sec)
	mm, ss = sec.divmod(60)
	hh, mm = mm.divmod(60)
	"%d:%d:%d" % [hh, mm, ss]
end


# Download stream information. Create a map of stream-names  => info
streams = JSON.parse(Net::HTTP.get('listen.di.fm', '/premium_high'), :symbolize_names => true)
streams = Hash[streams.map { |s| [s[:name], s] }]

# Get the currently playing stream URI
current_key = /(.+) -/.match(`mpc -f %name% current`)[1]

# Get the now playing information for this channel
info = Net::HTTP.get('api.audioaddict.com', '/v1/di/track_history')
info = JSON.parse(info, :symbolize_names => true)[streams[current_key][:id].to_s.to_sym]

position = Time.now.to_i - info[:started]
length = info[:length]

puts info[:artist]
puts info[:title]

puts seconds_to_time(position) + '/' + seconds_to_time(length)
