#!/bin/bash

if ! git status &> /dev/null; then
	echo "This is not a git repository"
	exit 1
fi

latest_tag=$(git tag -l v*.*.* --contains $(git rev-list --tags --max-count=1))

if [[ ! "$latest_tag" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
	echo "The most recent tag is not a semantic version tag"
	exit 1
fi

major=$(echo "${latest_tag:1}" | awk -F '.' '{print $1}')
minor=$(echo "${latest_tag}"   | awk -F '.' '{print $2}')
patch=$(echo "${latest_tag}"   | awk -F '.' '{print $3}' | awk -F '-' '{print $1}')

echo "Latest semantic version tag: ${major}.${minor}.${patch}"

case "$1" in
	major)
		echo "Bumping major version."
		major=$(( $major + 1 ))
		minor=0
		patch=0
		;;
	minor)
		echo "Bumping minor version."
		minor=$(( $minor + 1 ))
		patch=0
		;;
	patch|*)
		echo "Bumping patch version."
		patch=$(( $patch + 1 ))
		;;
esac

echo "New semantic version is: ${major}.${minor}.${patch}"
echo -n "Do you want to tag the current commit with that version? [y/N]: "

read answer

if [[ "$answer" =~ (y|Y|yes) ]]; then
	version="${major}.${minor}.${patch}"
	tag_message="Version $version"
	latest_message_version="$version"

	[ $major -eq 0 ] && tag_message="$tag_message Beta"
	[ $major -eq 0 ] && latest_message_version="$latest_message_version Beta"

	# Add the tag
	git tag -a v$version -m "$tag_message" > /dev/null

	echo "Latest tags:"
	git tag -n1 | tail -n5
else
	echo "Aborted. No tags where added!"
	exit
fi

echo -n "Would you like to push all branches containing this tag? [y/N]"

read answer

if [[ "$answer" =~ (y|Y|yes) ]]; then
	git push origin v$version $(git branch --contains v$version | cut -b 3-)
fi

